services:
  _defaults:
    autowire: true

  ICanBoogie\Prototype\Config:
    factory: [ '@ICanBoogie\ConfigProvider', config_for_class ]
    arguments:
      - ICanBoogie\Prototype\Config

  # Console

  ICanBoogie\Binding\Prototype\Console\ListPrototypesCommand:
    class: ICanBoogie\Binding\Prototype\Console\ListPrototypesCommand
    arguments:
      $style: '%console.style.table%'
    tags:
      - { name: console.command, command: 'prototype:list' }
      - { name: console.command, command: 'prototypes' }
